language: node_js
node_js:
  - node
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run deploy
before_install:
  - openssl aes-256-cbc -K $encrypted_a9123adda3ad_key -iv $encrypted_a9123adda3ad_iv -in deploy_key.enc -out deploy_key -d
